# 2.6矢量化表达式

In [1]:
#导入numpy包
import numpy as np

# 2.6.1数组算术运算

In [2]:
##############
#s数组形状相同
#数组与数组
x = np.array([[1, 2], [3, 4]])#构建数组

In [3]:
y = np.array([[5, 6], [7, 8]])#两个数组长度一致

In [4]:
x + y #加法

array([[ 6,  8],
       [10, 12]])

In [5]:
 y - x #减法

array([[4, 4],
       [4, 4]])

In [6]:
x * y #乘法

array([[ 5, 12],
       [21, 32]])

In [7]:
 y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [8]:
#标量与数组的运算，只有一个数字的结构
x * 2 #标量的乘法

array([[2, 4],
       [6, 8]])

In [9]:
 2 ** x #次方运算

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [10]:
 y / 2 #标量的除法

array([[2.5, 3. ],
       [3.5, 4. ]])

In [11]:
 (y / 2).dtype # 在整数数组和整数标量之间进行除法，在这种情况下，结果是64位双精度浮点数

dtype('float64')

In [12]:
###########
#如果数组对大小或形状不兼容的数组执行算术运算，则引发ValueError异常：
x = np.array([1, 2, 3, 4]).reshape(2, 2) #改变数组维度(重新调整矩阵的行数、列数、维数,改为2*2的数组）

In [13]:
z = np.array([1, 2, 3, 4])

In [14]:
 x / z #后缘维度不同，x维度为2，z维度为4，无法与形状（2,2）（4，）一起广播

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [15]:
#如果z有形状（2，），（2，1）或（1，2），那么它可以有效地广播到形状（2，2）
#shape为（1,2）的数组示例
z = np.array([[2, 4]])

In [16]:
z.shape

(1, 2)

In [17]:
 x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [18]:
#以上的例子也可用拼接函数操作，x/z相当于把z数组拼接成shape为（2,2）数组的示例
zz = np.concatenate([z, z], axis=0) #cocatenate拼接函数，axis=0表示第一个维度，沿着行方向进行拼接

In [19]:
zz

array([[2, 4],
       [2, 4]])

In [20]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

In [21]:
 #shape为（2,1）数组示例
z = np.array([[2], [4]])

In [22]:
z.shape

(2, 1)

In [23]:
x / z #将x除以z等于用数组zz除以x，即通过重复列向量z直到矩阵的维数与x数组的维数相同。

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [24]:
zz = np.concatenate([z, z], axis=1) #1表示按数组z列的方向拼接得到数组zz,x/z与x/zz的结果相同（numpy的广播规则）

In [25]:
zz

array([[2, 2],
       [4, 4]])

In [26]:
 x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [27]:
##########
#表2-6示例，两种方法效果相同
x = x + y

In [28]:
 x += y

# 2.6.2元素函数

In [29]:
#一个输入数组的运算符操作
#np.sin函数计算数组所有元素的正弦值
x = np.linspace(-1, 1, 11) #将-1——1间分成11份

In [30]:
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [31]:
 y = np.sin(np.pi * x) #y等于xpi的正弦

In [32]:
np.round(y, decimals=4) #y精确到小数点第四位

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [33]:
#对两个输入数组进行操作运算，最终返回一个输出数组
#在这个例子中添加（add）算符和“+”是等价的，并且是正规的
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
 np.sin(x) ** 2 + np.cos(x) ** 2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
###############
#赫维赛德函数是一个单位跃阶函数，非矢量化函数（不能用直线或曲线描述图形），
def heaviside(x):
    return 1 if x > 0 else 0

In [36]:
heaviside(-1)

0

In [37]:
heaviside(1.5)

1

In [38]:
#但赫德赛维函数不不适用numpy数组输入，会出现报错，例如：
x = np.linspace(-5, 5, 11) #构建数组x,从-5—5之间划分11份

In [39]:
 heaviside(x)
#报错理由：具有多个元素的数组的真值不明确。

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [40]:
#解决以上问题，可以使用np.矢量化标量Heaviside函数可以转换为矢量化函数，该函数使用NumPy数组作为输入
heaviside = np.vectorize(heaviside)

In [41]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [42]:
###############
#使用布尔值数组的算术，可以改善调用原始函数速度慢的问题，可以省略上例使用if语句的问题，更加快速简洁
def heaviside(x):
    return 1.0 * (x > 0)

# 2.6.3 聚合函数

In [43]:
#例如，, np.mean(data) 和 data.mean（）输出效果等价
data = np.random.normal(size=(15,15)) #data等于15*15数组的随机正态分布

In [44]:
 np.mean(data) #输出结果等价

0.12062517837735648

In [45]:
 data.mean() #输出结果等价

0.12062517837735648

In [46]:
###############（例1）
#对多维数组使用求和函数时，axis参数的运用情况
#例，对5*10*15的三维数组调用求和函数，输出数组的形状取决于轴参数的值
data = np.random.normal(size=(5, 10, 15)) #构建5*10*15随机正态分布的三维数组data

In [47]:
 data.sum(axis=0).shape #当axis=0时，按照“层”的方向进行求和，得到数据形状为10*15的二维数组

(10, 15)

In [48]:
data.sum(axis=(0, 2)).shape #当axis=(0,2)为二维时，，按照“层”和“行”的方向对原数组求和得到10*0的一维数组

(10,)

In [49]:
data.sum() #对数组求和为

-17.539620943699845

In [50]:
###########（例2）
#3*3列阵的数组，轴参数为0或1时，输出数组的加和
data = np.arange(1,10).reshape(3,3)

In [51]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
 data.sum()

45

In [53]:
data.sum(axis=0)#按列方向加和

array([12, 15, 18])

In [54]:
data.sum(axis=1) #按行方向加和

array([ 6, 15, 24])

# 2.6.4布尔数组和条件表达式

In [55]:
#############（例1）
#比较a、b两个运算符具有兼容的形状和大小，比较的结果是一个具有布尔值的新数组（dtype为np.bool)
a = np.array([1, 2, 3, 4])

In [56]:
 b = np.array([4, 3, 2, 1])

In [57]:
a < b

array([ True,  True, False, False])

In [58]:
############（例2）
#应用np.all或者np.any聚合函数,可以获得单个True或False值，可以替代if条件表达式比较数组a、b各元素大小
#np.all表示如果参数数组中的所有元素都小于数组b，则返回True
np.all(a < b)

False

In [59]:
#np.any表示如果参数数组中的任何元素不小于b，则返回True
np.any(a < b)

True

In [60]:
##############(例3)
#应用if条件表达式，判断a、b数组元素大小
if np.all(a < b):
    print("All elements in a are smaller than their corresponding element in b")
elif np.any(a < b):
     print("Some elements in a are smaller than their corresponding element in b")
else:
    print("All elements in b are smaller than their corresponding element in a")                

Some elements in a are smaller than their corresponding element in b


In [61]:
#当布尔值数组与标量进行运算时，布尔值数组会转化为数值数组，用0、1表示T和F
x = np.array([-2, -1, 0, 1, 2])

In [62]:
 x > 0

array([False, False, False,  True,  True])

In [63]:
#1乘以布尔值数组转化数值数组后的运算
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [64]:
#x乘以布尔值数组转化数值数组后的运算出的结果
x * (x > 0)

array([0, 0, 0, 1, 2])

In [65]:
###########（例4）
#定义一个脉冲函数，设置位置、高度、宽度，表达式（x>=位置）*（x<=（位置+宽度））两个布尔值数组的乘法，在这种情况下是乘法运算符充当元素与运算符。
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

In [66]:
 x = np.linspace(-5, 5, 11)

In [67]:
 pulse(x, position=1, height=1, width=5)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [68]:
#脉冲函数也可以实现使用NumPy的函数进行元素和运算，np.logical_and（逻辑与）函数可以代替上面的条件表达式
# 逻辑与函数表示对每个元素进行 and 运算，并返回 bool 值组成的数组
def pulse(x, position, height, width):
    return height * np.logical_and(x >= position, x <= (position + width))

In [69]:
###########
#np.where函数的用法为np.where(condition, x, y)，满足条件(condition)，输出x，不满足输出y,输出类型为布尔值
x = np.linspace(-4, 4, 9)
#x=array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [70]:
 np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [71]:
#对np.select筛选函数的应用，np.select(condlist, choicelist, default),第一个参数是操作数据所依据的条件，第二个参数根据condlist条件，索要执行的操作，第三个参数如果不满足条件的默认值
#返回值返回的是一个“ 列表”
np.select([x < -1, x < 2, x >= 2],
          [x**2 , x**3 , x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [72]:
# 对choose函数的应用，choose(a, choices,out=None, mode='raise')
#a必须是一个 int 型的 数组，并且 a 中的元素，必须是0~n-1之间的数;choices表示的是要操作的数组，要注意的是choices的数组的维度是一定要和a进行匹配的
#参数out：接收运算结果的数组，它的维度一定要和 a 是一样的，是可选参数。
#参数mode：默认的是raise，表示的是a数组中的元素不能超过 n ，她还有两个可选值;clip：将 a 中的 元素 如果小于0，则将其变为0，如果大于n-1，则变为n-1;wrap：将a中的值 value变为value mod n，即值除以n的余数。
#示例中a为一维，choices为二维，a的索引位置分别为（0,0）、（0,1），（0,2）、（1,3）、（1,4）、（1,5）、（2,6）、（2,7、（2,8）以此找到操作数组对应元素的位置。
#二维数组array([16.,  9.,  4.,  1.,  0.,  1.,  4.,  9., 16.]，[-64., -27.,  -8.,  -1.,   0.,   1.,   8.,  27.,  64.]，[256.,  81.,  16.,   1.,   0.,   1.,  16.,  81., 256.]]）
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2],
            [x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [73]:
#x=array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])
#非零函数的应用，使x的绝对值大于2返回数组非0时的索引的数组
np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8], dtype=int64),)

In [74]:
#使用非0函数与直接使用abs（x）>2索引数组的结果相同，但是它使用了特殊的索引，最后输出数组包含np.非零而不是布尔值数组索引
x[np.nonzero(abs(x) > 2)]

array([-4., -3.,  3.,  4.])

In [75]:
x[abs(x) > 2]

array([-4., -3.,  3.,  4.])

# 2.6.5设置操作

In [76]:
#np.unique函数的示例，创建具有唯一元素的新数组a、b(都有中有重复元素)，输出后a=(1,2,3);b=(2,3,4,5,6)
a = np.unique([1, 2, 3, 3])

In [77]:
b = np.unique([2, 3, 4, 4, 5, 6, 5])

In [78]:
#np.in1d函数中数组a中的元素是否重复出现在数组b中，并返回布尔值
np.in1d(a, b)

array([False,  True,  True])

In [79]:
#可以使用in关键字来测试一个以NumPy数组表示的集合中是否存在单个元素
1 in a

True

In [80]:
1 in b

False

In [81]:
#为了测试a是否是b的子集，我们可以使用np.inid函数，与前面的示例一样，与聚合函数一起使用np.all函数（如果参数数组中所有元素都非0，则返回Ture）
np.all(np.in1d(a, b)) #False=0,因此返回F,a不是b的子集

False

In [82]:
#np.union1d函数示例，返回一个数组，其中元素包含在两个给定数组的其中一个或两个数组中（并集）
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [83]:
#np.intersect1d函数示例，返回一个数组，其中的元素包含在两个给定数组中。（a、b交集）
np.intersect1d(a, b)

array([2, 3])

In [84]:
#np.setdiff1d函数示例，返回一个数组，该数组包含的元素包含在两个给定数组，即a集元素不包含b集元素的部分，为[1]
np.setdiff1d(a, b)

array([1])

In [85]:
#即b集元素不包含a集元素的部分，为[4,5,6]
np.setdiff1d(b, a)

array([4, 5, 6])

# 2.6.6对矩阵的操作

In [86]:
#data等于0-8的数组重新改变形状成3*3的二维矩阵
data = np.arange(9).reshape(3, 3)

In [87]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
#np.transpose转置函数转换data的行和列
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [89]:
#转置函数在ndarray中也作为一个方法存在，并且作为一个特殊的方法名ndarray.T。对于一个任意的N维数组，转置操作会反转所有的轴
#创建一个5维数组
data = np.random.randn(1, 2, 3, 4, 5)

In [90]:
data.shape

(1, 2, 3, 4, 5)

In [91]:
#转置后的5维数组的形状变成5*4*3*2*1
data.T.shape

(5, 4, 3, 2, 1)

# 2.7向量与矩阵的运算

In [92]:
#要计算两个矩阵A和B的乘积，大小为N×M和M×P，从而得到一个大小为N×P的矩阵
#
#示例：构建一个从1-6排序，2*3的二维数组A
A = np.arange(1, 7).reshape(2, 3)

In [93]:
 A

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
 #构建从1-6排序，形状为3*2的数组B
B = np.arange(1, 7).reshape(3, 2)

In [95]:
 B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [96]:
#np.dot函数表示的是两个给定数组的矩阵乘积，A*B最终得到2*2的输出数组
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [97]:
#数组B乘以数组A得到3*3的输出数组
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [98]:
#
#np.dot函数也可用于矩阵向量乘法（即，表示矩阵的二维数组与表示向量的一维数组相乘）。例如:
#创建0-8,3*3的数组A
A = np.arange(9).reshape(3, 3)

In [99]:
 A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
#x为0-2的一维数组
x = np.arange(3)

In [101]:
 x

array([0, 1, 2])

In [102]:
#二维数组A乘以一维向量x，可以得到一维输出数组
np.dot(A, x)

array([ 5, 14, 23])

In [103]:
#x可以是形状（1，3）的二维数组，也可以是形状（3，）的一维数组。除了功能np.dot，在ndarray中也有一个对应的方法点，可以如下例使用
A.dot(x)

array([ 5, 14, 23])

In [104]:
# 
#非平凡的矩阵乘法表达式在使用其中一个时常常变得复杂且难以阅读np.dot或者np.ndarray.dot. 例如，即使是一个相对简单的矩阵表达式，如用于相似变换的矩阵表达式a′=BAB−1，也必须用相对隐蔽的嵌套表达式来表示
A = np.random.rand(3,3)

In [105]:
 B = np.random.rand(3,3)

In [106]:
 # np.linalg.inv函数表示对矩阵求逆，第一个例子运用的是numpy的表达式，表示Ap=B*A*B-1
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))

In [107]:
#也同样可以ndarray的方法，同样也能够表示Ap=B*A*B-1
Ap = B.dot(A.dot(np.linalg.inv(B)))

In [108]:
#NumPy为ndarray命名的matrix提供了另一种数据结构，它还提供了一些方便的特殊属性
#将数组A转化为矩阵A,数组B为矩阵B
A = np.matrix(A)

In [109]:
 B = np.matrix(B)

In [110]:
 #matrix()还可以在后面加 .H 得到共轭矩阵, 加 .I 得到逆矩阵,加.T得到转置矩阵
#Ap等于矩阵B*矩阵A*B的逆矩阵
Ap = B * A * B.I

In [111]:
#
#使用matrix类函数存在一些问题，matrix必须是2维的,但是 numpy arrays 可以是多维的,并且如果一个程序里面既有matrix 又有array会降低程序的可读性，因此可以通过下面的两条命令轻松的实现两者之间的转换：np.asmatrix和np.asarray
#A、B都转换成matrix
A = np.asmatrix(A)

In [112]:
 B = np.asmatrix(B)

In [113]:
 Ap = B * A * B.I

In [114]:
#最后将Ap转化成array 
Ap = np.asarray(Ap)

In [115]:
#
#下面的例子表示向量的两个数组之间的内积（标量积）可以使用np.inner函数
#x=[0, 1, 2]
np.inner(x, x)

5

In [116]:
#或者使用np.dot函数也可以得到相同的结果
np.dot(x, x)

5

In [117]:
#np.inner和np.dot主要的区别是np.inner需要两个具有相同维度的输入参数，而np.dot可以分别取形状为1×N和N×1的输入向量
#
#np.newaxis函数的作用是在原数组上增加一个维度，这里表示的是增加一维，变成3*1的二维数组y
y = x[:, np.newaxis]

In [118]:
y

array([[0],
       [1],
       [2]])

In [119]:
#np.dot可以取1*N和N*1的向量相乘，y的转置乘以y输出结果是一个数5
np.dot(y.T, y)

array([[5]])

In [120]:
#示例：外积
#内积将两个向量映射到一个标量，而外积则执行将两个向量映射到一个矩阵的互补运算。
x = np.array([1, 2, 3])

In [121]:
#利用np.outer函数求向量x外积
np.outer(x, x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [122]:
#外积也可以用Kronecker积来计算，然而，与np.outer相比，如果输入数组分别具有形状（M，N）和（P，Q），则生成形状（M*P，N*Q）的输出数组。因此，对于长度为M和P的两个一维数组，得到的数组具有形状（M*P，）
#M=3,P=3，输出数组形状为（9，）9个元素的一维数组
np.kron(x, x)

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [123]:
#括号里前半部分表示形状为（3,1）的数组，后半部分表示（1，3）三维数组。它们的乘积按照上述乘积规则可以得到形状为（3,3）输出数组
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [124]:
#
#这个尼泊尔克朗函数可用于计算任意维数组的张量积（但两个输入必须具有相同的轴数）。例如，要计算两个2×2矩阵的张量积
#np.ones函数表示返回一个全1的二维数组，np.identity函数表示返回一个2维主对角线为1，其他元素为0的方阵，这两个数组计算外积最终得到4*4的输出数组
np.kron(np.ones((2,2)), np.identity(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [125]:
np.kron(np.identity(2), np.ones((2,2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [126]:
#
#当使用多维数组时，通常可以使用爱因斯坦的求和约定简洁地表示常见的数组操作，在该约定中，假设对表达式中多次出现的每个索引进行隐式求和。
#np.einsum函数评估爱因斯坦多维数组的求和约定。
#具体使用方式：假设两个向量x和y之间的标量积用xnyn表示，两个矩阵A和B的矩阵乘法用AmkBkn表示，函数的第一个参数是一个索引表达式，后跟表达式中包含的任意数量的数组。索引表达式是一个带有逗号分隔索引的字符串，其中每个逗号分隔每个数组的索引。每个数组可以有任意数量的索引。
#例如，下面的例子“n,n”是第一个参数（索引表达式），n表示x和y的下标（x和y向量相乘后求和）
x = np.array([1, 2, 3, 4])

In [127]:
y = np.array([5, 6, 7, 8])

In [128]:
np.einsum("n,n", x, y)

70

In [129]:
#使用inner函数求两个向量的内积也可以得到相同的结果
np.inner(x, y)

70

In [130]:
#类似地，矩阵乘法AmkBkn可以用np.einsum以及索引表达式“mk，kn”
#
A = np.arange(9).reshape(3, 3)

In [131]:
 B = A.T

In [132]:
 #最后输出m*n的矩阵
#优点：einsum允许组合相乘，相加和转置等numpy函数帮助我们更快、更高效的完成任务，爱因斯坦求和约定在处理多维数组时特别方便，因为定义操作的索引表达式明确了执行哪个操作以及沿着哪个轴执行。
np.einsum("mk,kn", A, B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [133]:
#allture反映enisum计算后输出矩阵的每个元素是否与dot计算结果相等
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

True

# 2.9Numpy实例练习

In [134]:
# 实例1

In [135]:
import numpy as np

arr1 = np.array([[0, 0, 0],[1, 1, 1],[2, 2, 2], [3, 3, 3]])  #arr1.shape = (4,3)
arr2 = np.array([1, 2, 3])    #arr2.shape = (3,)
arr_sum = arr1 + arr2
print(arr_sum)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [136]:
#实例2

In [137]:
import numpy as np

# 2
data=np.ones((5,5))
print(data)
data[[1,2,3],:]=0
print(data)
data[:,[0,4]]=1
print(data)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [138]:
#实例3

In [139]:
data=np.arange(0,11)
print(data)
data=np.where(data>1,0-(data),data)
data=np.where(data<-9,0-data,data)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1 -2 -3 -4 -5 -6 -7 -8 -9 10]


In [140]:
#实例4

In [141]:
import numpy as np 
 
a = np.array([[1,1,1],[0,2,5],[2,5,-1]]) 
 
print ('数组 A：')
print (a)
ainv = np.linalg.inv(a) 
 
print ('A 的逆：')
print (ainv)
 
print ('矩阵 Y：')
y = np.array([[6],[-4],[27]]) 
print (y)
 
print ('计算：A^(-1)Y：')
x = np.linalg.solve(a,y) 
print("通过np.linalg.solve(a,y)计算得：")
print (x)
# 这就是线性方向 x = 5, y = 3, z = -2 的解
# 结果也可以使用以下函数获取
print("通过np.dot(ainv,y)计算得：")
x2 = np.dot(ainv,y)
print(x2)

数组 A：
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
A 的逆：
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
矩阵 Y：
[[ 6]
 [-4]
 [27]]
计算：A^(-1)Y：
通过np.linalg.solve(a,y)计算得：
[[ 5.]
 [ 3.]
 [-2.]]
通过np.dot(ainv,y)计算得：
[[ 5.]
 [ 3.]
 [-2.]]
