# Chapter 2: Vectors, matrices and multidimensional arrays

陶欣雨
22019207061

In [1]:
import numpy as np

## The NumPy array object

In [2]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
type(data)

numpy.ndarray

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim

2

In [6]:
data.shape

(3, 2)

In [7]:
data.size

6

In [8]:
data.dtype

dtype('int32')

In [9]:
data.nbytes

24

## Data types

In [10]:
np.array([1, 2, 3], dtype=np.int)

array([1, 2, 3])

In [11]:
np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [12]:
np.array([1, 2, 3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
data = np.array([1, 2, 3], dtype=np.float)
data

array([1., 2., 3.])

In [15]:
data.dtype

dtype('float64')

In [16]:
data = np.array([1, 2, 3], dtype=np.int)

In [17]:
data.dtype

dtype('int32')

In [18]:
data

array([1, 2, 3])

In [19]:
data = np.array([1, 2, 3], dtype=np.float)

In [20]:
data

array([1., 2., 3.])

In [25]:
data = data.astype(np.int)
print(data)
print(data.dtype)

[1 2 3]
int32


In [28]:
d1 = np.array([1, 2, 3], dtype=float)

In [29]:
d2 = np.array([1, 2, 3], dtype=complex)

In [30]:
d2.dtype

dtype('complex128')

In [31]:
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [32]:
(d1 + d2).dtype

dtype('complex128')

In [33]:
np.sqrt(np.array([-1, 0, 1]))

C:\Users\taoxi\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [34]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

### Real and imaginary parts

In [35]:
data = np.array([1, 2, 3], dtype=complex)

In [36]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [37]:
data.real

array([1., 2., 3.])

In [38]:
data.imag

array([0., 0., 0.])

## Creating arrays

### Arrays created from lists and other array-like objects

In [42]:
data = np.array([1, 2, 3, 4])

In [43]:
data.ndim

1

In [44]:
data.shape

(4,)

In [50]:
data = np.array([[1, 2], [3, 4]])

In [51]:
data.ndim

2

In [52]:
data.shape

(2, 2)

### Arrays filled with constant values

In [53]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.ones(4)

array([1., 1., 1., 1.])

In [55]:
data = np.ones(4)

In [56]:
data.dtype

dtype('float64')

In [57]:
data = np.ones(4, dtype=np.int64)

In [58]:
data.dtype

dtype('int64')

In [59]:
x1 = 5.4 * np.ones(10)
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [60]:
x2 = np.full(10, 5.4)
x2

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [61]:
x1 = np.empty(5)
x1

array([9.99731764e-312, 3.21450328e+164, 1.85692977e+216, 1.99392236e-077,
       1.11253693e-306])

In [62]:
x1.fill(3.0)

In [63]:
x1

array([3., 3., 3., 3., 3.])

In [64]:
x2 = np.full(5, 3.0)

In [65]:
x2

array([3., 3., 3., 3., 3.])

### Arrays filled with incremental sequences

In [66]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [67]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Arrays filled with logarithmic sequences

In [69]:
np.logspace(0, 2, 5)  

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

### Mesh-grid arrays

In [70]:
x = np.array([-1, 0, 1])

In [71]:
y = np.array([-2, 0, 2])

In [72]:
X, Y = np.meshgrid(x, y)

In [73]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [74]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [75]:
Z = (X + Y) ** 2

In [76]:
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]], dtype=int32)

### Creating uninitialized arrays

In [79]:
data = np.empty(3, dtype=np.float)
data

array([0., 0., 0.])

### Creating arrays with properties of other arrays

In [80]:
def f(x):
    y = np.ones_like(x)
    return y

### Creating matrix arrays

In [81]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [83]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [84]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [87]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## Index and slicing

### One-dimensional arrays

In [88]:
a = np.arange(0, 11)

In [89]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
a[0]  # the first element

0

In [91]:
a[-1] # the last element

10

In [92]:
a[4]  # the fifth element, at index 4

4

In [93]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [95]:
a[:5]

array([0, 1, 2, 3, 4])

In [96]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [97]:
a[::-2]


array([10,  8,  6,  4,  2,  0])

## Multidimensional arrays

In [100]:
f = lambda m, n: n + 10 * m
f

<function __main__.<lambda>(m, n)>

In [101]:
A = np.fromfunction(f, (6, 6), dtype=int)

In [102]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [103]:
A[:, 1]

array([ 1, 11, 21, 31, 41, 51])

In [104]:
A[1, :] 

array([10, 11, 12, 13, 14, 15])

In [105]:
A[:3, :3] 

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [106]:
A[3:, :3] 

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [107]:
A[::2, ::2] 

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [108]:
A[1::2, 1::3]

array([[11, 14],
       [31, 34],
       [51, 54]])

### Views

In [109]:
B = A[1:5, 1:5]

In [110]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [111]:
B[:, :] = 0

In [112]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [113]:
C = B[1:3, 1:3].copy()

In [114]:
C

array([[0, 0],
       [0, 0]])

In [115]:
C[:, :] = 1 

In [116]:
C

array([[1, 1],
       [1, 1]])

In [117]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Fancy indexing and Boolean-valued indexing

In [118]:
A = np.linspace(0, 1, 11)

In [119]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [120]:
A[[0, 2, 4]]

array([0. , 0.2, 0.4])

In [121]:
A > 0.5 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [122]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [123]:
A = np.arange(10)

In [124]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
indices = [2, 4, 6]
indices

[2, 4, 6]

In [126]:
B = A[indices]
B

array([2, 4, 6])

In [128]:
B[0] = -1 
B

array([-1,  4,  6])

In [129]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
A[indices] = -1

In [131]:
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [132]:
A = np.arange(10)

In [133]:
B = A[A > 5]
B

array([6, 7, 8, 9])

In [134]:
B[0] = -1  
B

array([-1,  7,  8,  9])

In [135]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
A[A > 5] = -1

In [137]:
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

## Reshaping and resizing

In [138]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [139]:
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [140]:
data.reshape(4)

array([1, 2, 3, 4])

In [141]:
data = np.array([[1, 2], [3, 4]])

In [142]:
data

array([[1, 2],
       [3, 4]])

In [143]:
data.flatten()

array([1, 2, 3, 4])

In [144]:
data.flatten().shape

(4,)

In [145]:
data = np.arange(0, 5)

In [146]:
column = data[:, np.newaxis]

In [147]:
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [148]:
row = data[np.newaxis, :]

In [149]:
row

array([[0, 1, 2, 3, 4]])

In [150]:
data = np.arange(5)

In [151]:
data

array([0, 1, 2, 3, 4])

In [152]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [153]:
data = np.arange(5)

In [154]:
data

array([0, 1, 2, 3, 4])

In [155]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [156]:
data = data[:, np.newaxis]

In [157]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

## Vectorized expressions

### Arithmetic operations

In [158]:
x = np.array([[1, 2], [3, 4]]) 

In [159]:
y = np.array([[5, 6], [7, 8]])

In [160]:
x + y

array([[ 6,  8],
       [10, 12]])

In [161]:
y - x

array([[4, 4],
       [4, 4]])

In [162]:
x * y

array([[ 5, 12],
       [21, 32]])

In [163]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [164]:
x * 2

array([[2, 4],
       [6, 8]])

In [165]:
2 ** x

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [166]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [167]:
(y / 2).dtype

dtype('float64')

In [168]:
x = np.array([1, 2, 3, 4]).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [169]:
z = np.array([1, 2, 3, 4])

In [170]:
x / z

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [171]:
z = np.array([[2, 4]])

In [172]:
z

array([[2, 4]])

In [173]:
z.shape

(1, 2)

In [174]:
x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [176]:
zz = np.concatenate([z, z], axis=0)

In [177]:
zz

array([[2, 4],
       [2, 4]])

In [178]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

In [179]:
z = np.array([[2], [4]])
z

array([[2],
       [4]])

In [180]:
z.shape

(2, 1)

In [181]:
x / z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [182]:
zz = np.concatenate([z, z], axis=1)

In [183]:
zz

array([[2, 2],
       [4, 4]])

In [184]:
x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [185]:
x = np.array([[1, 3], [2, 4]])
x = x + y
x

array([[ 6,  9],
       [ 9, 12]])

In [186]:
x = np.array([[1, 3], [2, 4]])
x += y
x

array([[ 6,  9],
       [ 9, 12]])

### Elementwise functions

In [187]:
x = np.linspace(-1, 1, 11)

In [188]:
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [189]:
y = np.sin(np.pi * x)

In [190]:
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [191]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [192]:
np.sin(x) ** 2 + np.cos(x) ** 2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [193]:
def heaviside(x):
    return 1 if x > 0 else 0

In [194]:
heaviside(-1)

0

In [195]:
heaviside(1.5)

1

In [196]:
x = np.linspace(-5, 5, 11)

In [197]:
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [198]:
heaviside = np.vectorize(heaviside)

In [199]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [200]:
def heaviside(x):
    return 1.0 * (x > 0)

### Aggregate functions

In [201]:
data = np.random.normal(size=(15,15))

In [202]:
np.mean(data)

-0.0324541710484768

In [203]:
data.mean()

-0.0324541710484768

In [204]:
data = np.random.normal(size=(5, 10, 15))

In [205]:
data.sum(axis=0).shape

(10, 15)

In [206]:
data.sum(axis=(0, 2)).shape

(10,)

In [207]:
data.sum()

-13.319928702773598

In [208]:
data = np.arange(1,10).reshape(3,3)

In [209]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [210]:
data.sum()

45

In [211]:
data.sum(axis=0)

array([12, 15, 18])

In [212]:
data.sum(axis=1)

array([ 6, 15, 24])

### Boolean arrays and conditional expressions

In [213]:
a = np.array([1, 2, 3, 4])

In [214]:
b = np.array([4, 3, 2, 1])

In [215]:
a < b

array([ True,  True, False, False])

In [216]:
np.all(a < b)

False

In [217]:
np.any(a < b)

True

In [218]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding element in b")
elif np.any(a < b):
    print("Some elements in a are smaller than their corresponding elemment in b")
else:
    print("All elements in b are smaller than their corresponding element in a")

Some elements in a are smaller than their corresponding elemment in b


In [219]:
x = np.array([-2, -1, 0, 1, 2])

In [220]:
x > 0

array([False, False, False,  True,  True])

In [221]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [222]:
x * (x > 0)

array([0, 0, 0, 1, 2])

In [223]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

In [224]:
x = np.linspace(-5, 5, 11)

In [225]:
pulse(x, position=-2, height=1, width=5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [226]:
pulse(x, position=1, height=1, width=5)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [227]:
def pulse(x, position, height, width):
    return height * np.logical_and(x >= position, x <= (position + width))

In [231]:
x = np.linspace(-4, 4, 9)
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [232]:
np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [233]:
np.select([x < -1, x < 2, x >= 2],
          [x**2  , x**3 , x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [234]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], 
          [x**2,    x**3,    x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [235]:
x[abs(x) > 2]

array([-4., -3.,  3.,  4.])

In [236]:
np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8], dtype=int64),)

In [237]:
x[np.nonzero(abs(x) > 2)]

array([-4., -3.,  3.,  4.])

# Set operations

In [238]:
a = np.unique([1,2,3,3])
a

array([1, 2, 3])

In [239]:
b = np.unique([2,3,4,4,5,6,5])
b

array([2, 3, 4, 5, 6])

In [240]:
np.in1d(a, b)

array([False,  True,  True])

In [241]:
1 in a

True

In [242]:
1 in b

False

In [243]:
np.all(np.in1d(a, b))

False

In [244]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [245]:
np.intersect1d(a, b)

array([2, 3])

In [246]:
np.setdiff1d(a, b)

array([1])

In [247]:
np.setdiff1d(b, a)

array([4, 5, 6])

### Operations on arrays

In [248]:
data = np.arange(9).reshape(3, 3)

In [249]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [250]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [252]:
data = np.random.randn(1, 2, 3, 4, 5)
data

array([[[[[ 0.64614335, -0.77083791,  0.57562582, -0.80024754,
           -0.85013848],
          [ 0.33683219,  0.57225507,  0.40711599,  1.52682734,
           -0.98547994],
          [ 0.01093887, -0.4671318 ,  0.98423946, -0.84191056,
           -1.91941053],
          [ 0.29078986,  0.41414966, -1.56380552,  0.15640879,
           -0.22963834]],

         [[ 0.45850698, -0.41925324, -1.35087387,  0.4939103 ,
            1.73029292],
          [-1.23952829,  1.87709152, -0.33153964, -1.01848879,
           -0.1155446 ],
          [ 1.36103553,  1.16316163,  0.02329911,  0.07335085,
           -0.89118476],
          [-0.73374756,  0.69202144,  0.14759796, -1.26854568,
           -0.09545061]],

         [[ 0.09229633, -1.14042805,  0.27349633,  0.56592911,
           -0.15722429],
          [-1.20977402, -1.77068085, -0.67515623,  2.92070805,
           -1.35740993],
          [ 0.17077971, -0.68506036, -0.17350585,  1.31695986,
           -1.30361106],
          [-0.73689926,  0.3

In [253]:
data.shape

(1, 2, 3, 4, 5)

In [254]:
data.T.shape

(5, 4, 3, 2, 1)

## Matrix and vector operations

In [255]:
A = np.arange(1, 7).reshape(2, 3)

In [256]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [257]:
B = np.arange(1, 7).reshape(3, 2)

In [258]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [259]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [260]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [261]:
A = np.arange(9).reshape(3, 3)

In [262]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [263]:
x = np.arange(3)

In [264]:
x

array([0, 1, 2])

In [265]:
np.dot(A, x)

array([ 5, 14, 23])

In [266]:
A.dot(x)

array([ 5, 14, 23])

In [267]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)

In [268]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))
Ap

array([[-4.17022968,  4.06394948,  0.08053072],
       [-4.73455551,  4.61690912,  0.23530372],
       [-5.79111909,  5.84047693,  0.29706489]])

In [269]:
Ap = B.dot(A.dot(np.linalg.inv(B)))
Ap

array([[-4.17022968,  4.06394948,  0.08053072],
       [-4.73455551,  4.61690912,  0.23530372],
       [-5.79111909,  5.84047693,  0.29706489]])

In [271]:
A = np.matrix(A)
A

matrix([[0.05191154, 0.61804134, 0.41152687],
        [0.53929765, 0.51062089, 0.29678337],
        [0.7481356 , 0.92682336, 0.1812119 ]])

In [272]:
B = np.matrix(B)
B

matrix([[0.86171817, 0.08076888, 0.188065  ],
        [0.92173151, 0.25099464, 0.28944905],
        [0.95220905, 0.80612715, 0.25628224]])

In [273]:
Ap = B * A * B.I
Ap

matrix([[-4.17022968,  4.06394948,  0.08053072],
        [-4.73455551,  4.61690912,  0.23530372],
        [-5.79111909,  5.84047693,  0.29706489]])

In [274]:
A = np.asmatrix(A)
A

matrix([[0.05191154, 0.61804134, 0.41152687],
        [0.53929765, 0.51062089, 0.29678337],
        [0.7481356 , 0.92682336, 0.1812119 ]])

In [275]:
B = np.asmatrix(B)
B

matrix([[0.86171817, 0.08076888, 0.188065  ],
        [0.92173151, 0.25099464, 0.28944905],
        [0.95220905, 0.80612715, 0.25628224]])

In [276]:
Ap = B * A * B.I
Ap

matrix([[-4.17022968,  4.06394948,  0.08053072],
        [-4.73455551,  4.61690912,  0.23530372],
        [-5.79111909,  5.84047693,  0.29706489]])

In [277]:
Ap = np.asarray(Ap)
Ap

array([[-4.17022968,  4.06394948,  0.08053072],
       [-4.73455551,  4.61690912,  0.23530372],
       [-5.79111909,  5.84047693,  0.29706489]])

In [278]:
np.inner(x, x)

5

In [279]:
np.dot(x, x)

5

In [280]:
y = x[:, np.newaxis]

In [281]:
y

array([[0],
       [1],
       [2]])

In [282]:
np.dot(y.T, y)

array([[5]])

In [283]:
x = np.array([1, 2, 3])

In [284]:
np.outer(x, x) 

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [285]:
np.kron(x, x) 

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [286]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [287]:
np.kron(np.ones((2,2)), np.identity(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [288]:
np.kron(np.identity(2), np.ones((2,2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [289]:
x = np.array([1, 2, 3, 4])

In [290]:
y = np.array([5, 6, 7, 8])

In [291]:
np.einsum("n,n", x, y)

70

In [292]:
np.inner(x, y)

70

In [293]:
A = np.arange(9).reshape(3, 3)

In [294]:
B = A.T

In [295]:
np.einsum("mk,kn", A, B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [296]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

True