In [1]:
import numpy as np
 
# sigmoid
def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

# input
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])

# output
y = np.array([[0,0,1,1]]).T

np.random.seed(1)
#initialize weights
weight0 = 2*np.random.random((3,1)) - 1
print("weight0:")
print(weight0)
 
for iter in range(10000):
    l0 = X
    output = sigmoid(np.dot(l0,weight0))               #predict
    output_error = y - output                           #loss
    output_delta = output_error * sigmoid(output,True)
    
    # update weights更新我们的网络
    weight0 += np.dot(l0.T,output_delta)

print("weight:")
print(weight0)
print("output")
print (output)

weight0:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
weight:
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
output
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]
