# 第二章: Vectors, matrices and multidimensional arrays

In [257]:
import numpy as np

## The NumPy array object

In [258]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [259]:
type(data)

numpy.ndarray

In [260]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [261]:
data.ndim  #ndim返回的是数组的维度，返回的只有一个数，该数即表示数组的维度。

2

In [262]:
data.shape #表示各位维度大小的元组。返回的是一个元组。

(3, 2)

In [263]:
data.size #读取数组长度。

6

In [264]:
data.dtype #一个用于说明数组数据类型的对象。

dtype('int32')

In [265]:
data.nbytes #nbytes属性是数组中的所有数据消耗掉的字节数

24

## Data types

In [266]:
np.array([1, 2, 3], dtype=np.int)

array([1, 2, 3])

In [267]:
np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [268]:
np.array([1, 2, 3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [269]:
data = np.array([1, 2, 3], dtype=np.float)

In [270]:
data

array([1., 2., 3.])

In [271]:
data.dtype

dtype('float64')

In [272]:
data = np.array([1, 2, 3], dtype=np.int)

In [273]:
data.dtype

dtype('int32')

In [274]:
data

array([1, 2, 3])

In [275]:
data = np.array([1, 2, 3], dtype=np.float)

In [276]:
data

array([1., 2., 3.])

In [277]:
data.astype(np.int)

array([1, 2, 3])

In [278]:
d1 = np.array([1, 2, 3], dtype=float)

In [279]:
d2 = np.array([1, 2, 3], dtype=complex)

In [280]:
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [281]:
(d1 + d2).dtype

dtype('complex128')

In [282]:
np.sqrt(np.array([0, 1, 2]))

array([0.        , 1.        , 1.41421356])

In [283]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

### Real and imaginary parts

In [284]:
data = np.array([1, 2, 3], dtype=complex)

In [285]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [286]:
data.real

array([1., 2., 3.])

In [287]:
data.imag

array([0., 0., 0.])

## Creating arrays

### Arrays created from lists and other array-like objects

In [288]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [289]:
data.ndim

1

In [290]:
data.shape

(3,)

In [291]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [292]:
data.ndim

1

In [293]:
data.shape

(3,)

### Arrays filled with constant values

In [294]:
np.zeros((2, 3)) #创建指定形状的数组，数组中的值都为0，

array([[0., 0., 0.],
       [0., 0., 0.]])

In [295]:
np.ones(4) #返回一个指定形状和数据类型的新数组，并且数组中的值都为1。

array([1., 1., 1., 1.])

In [296]:
data = np.ones(4)

In [297]:
data.dtype

dtype('float64')

In [298]:
data = np.ones(4, dtype=np.int64)

In [299]:
data.dtype

dtype('int64')

In [300]:
x1 = 5.4 * np.ones(10)
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [301]:
x2 = np.full([2,3], 5.4)  #numpy.full(shape, fill_value, dtype=None, order='C')[source]  返回一个根据指定shape和type,并用fill_value填充的新数组。
x2

array([[5.4, 5.4, 5.4],
       [5.4, 5.4, 5.4]])

In [302]:
x1 = np.empty(5,int) #根据给定的维度和数值类型返回一个新的数组，其元素不进行初始化。
x1

array([2, 3, 4, 5, 6])

In [303]:
x1.fill(3.0) #将数组中的值填充为value中的值

In [304]:
x1

array([3, 3, 3, 3, 3])

In [305]:
x2 = np.full(5, 3.0)

In [306]:
x2

array([3., 3., 3., 3., 3.])

### Arrays filled with incremental sequences

In [307]:
np.arange(0.0, 10, 1) #arange通过使用给定间隔内的均匀间隔的值来创建数组。注意得到的结果数组不包含终值。

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [308]:
np.linspace(0, 10, 11) #指定的间隔内返回均匀间隔的数字，默认不包含终值，可设定包含空值。

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Arrays filled with logarithmic sequences

In [309]:
np.logspace(0, 2, 5)  # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

### Mesh-grid arrays

In [310]:
x = np.array([-1, 0, 1])

In [311]:
y = np.array([-2, 0])

In [312]:
X, Y = np.meshgrid(x, y)#生成网格矩阵

In [313]:
X

array([[-1,  0,  1],
       [-1,  0,  1]])

In [314]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0]])

In [315]:
Z = (X + Y) ** 2

In [316]:
Z

array([[9, 4, 1],
       [1, 0, 1]], dtype=int32)

### Creating uninitialized arrays

In [317]:
np.empty(3, dtype=np.float) #初始化数组

array([            nan,             nan, 2.12199579e-314])

### Creating arrays with properties of other arrays

In [318]:
def f(x):
    y = np.ones_like(x)
    # compute with x and y
    return y

### Creating matrix arrays

In [319]:
np.identity(4) #生成标准对角矩阵

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [320]:
np.eye(3, k=1) #生成一个对角线是1，其他对角线都为0的数组

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [321]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [322]:
np.diag(np.arange(0, 20, 5))#生成对角矩阵

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## Index and slicing

### One-dimensional arrays

In [323]:
a = np.arange(0, 11)

In [324]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [325]:
a[0]  # the first element

0

In [326]:
a[-1] # the last element

10

In [327]:
a[4]  # the fifth element, at index 4

4

In [328]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [329]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [330]:
a[:5]

array([0, 1, 2, 3, 4])

In [331]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [332]:
a[::-2]


array([10,  8,  6,  4,  2,  0])

## Multidimensional arrays

In [333]:
f = lambda m, n: n + 10 * m #快速函数

In [334]:
A = np.fromfunction(f, (6, 6), dtype=int)

In [335]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [336]:
A[:, 1]  # the second column

array([ 1, 11, 21, 31, 41, 51])

In [337]:
A[1, :]  # the second row

array([10, 11, 12, 13, 14, 15])

In [338]:
A[:3, :3]  # upper half diagonal block matrix

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [339]:
A[3:, :3]  # lower left off-diagonal block matrix

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [340]:
A[::2, ::2]  # every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [341]:
A[1::2, 1::3]  # every second element starting from 1, 1

array([[11, 14],
       [31, 34],
       [51, 54]])

### Views

In [342]:
B = A[1:5, 1:5]

In [343]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [344]:
B[:, :] = 0

In [345]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [346]:
C = B[1:3, 1:3].copy()

In [347]:
C

array([[0, 0],
       [0, 0]])

In [348]:
C[:, :] = 1  # this does not affect B since C is a copy of the view B[1:3, 1:3]

In [349]:
C

array([[1, 1],
       [1, 1]])

In [350]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Fancy indexing and Boolean-valued indexing

In [351]:
A = np.linspace(0, 1, 11)

In [352]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [353]:
A[[0, 2, 4]]

array([0. , 0.2, 0.4])

In [354]:
A > 0.5 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [355]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [356]:
A = np.arange(10)

In [357]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [358]:
indices = [2, 4, 6]

In [359]:
B = A[indices]

In [360]:
B[0] = -1  # this does not affect A

In [361]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [362]:
A[indices] = -1

In [363]:
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [364]:
A = np.arange(10)

In [365]:
B = A[A > 5]

In [366]:
B[0] = -1  # this does not affect A

In [367]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [368]:
A[A > 5] = -1

In [369]:
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

## Reshaping and resizing

In [370]:
data = np.array([[1, 2], [3, 4]])

In [371]:
np.reshape(data, (1, 4))#重新定义形状

array([[1, 2, 3, 4]])

In [372]:
data.reshape(4)

array([1, 2, 3, 4])

In [373]:
data = np.array([[1, 2], [3, 4],[5,6]])

In [374]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [375]:
data.flatten()#返回一个折叠成一维的数组。

array([1, 2, 3, 4, 5, 6])

In [376]:
data.flatten().shape

(6,)

In [377]:
data = np.arange(0, 5)

In [378]:
column = data[:, np.newaxis]

In [379]:
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [380]:
row = data[np.newaxis, :]

In [381]:
row

array([[0, 1, 2, 3, 4]])

In [382]:
data = np.arange(5)

In [383]:
data

array([0, 1, 2, 3, 4])

In [384]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [385]:
data = np.arange(5)

In [386]:
data

array([0, 1, 2, 3, 4])

In [387]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [388]:
data = data[:, np.newaxis]

In [389]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

## Vectorized expressions

### Arithmetic operations

In [390]:
x = np.array([[1, 2], [3, 4]]) 

In [391]:
y = np.array([[5, 6], [7, 8]])

In [392]:
x + y # 数组运算

array([[ 6,  8],
       [10, 12]])

In [393]:
y - x

array([[4, 4],
       [4, 4]])

In [394]:
x * y

array([[ 5, 12],
       [21, 32]])

In [395]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [396]:
x * 2

array([[2, 4],
       [6, 8]])

In [397]:
2 ** x

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [398]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [399]:
(y / 2).dtype

dtype('float64')

In [400]:
x = np.array([1, 2, 3, 4]).reshape(2,2)

In [401]:
z = np.array([1, 2, 3, 4])

In [402]:
z = np.array([[2, 4]])

In [403]:
z

array([[2, 4]])

In [404]:
z.shape

(1, 2)

In [405]:
x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [406]:
zz = np.concatenate([z, z], axis=0)

In [407]:
zz

array([[2, 4],
       [2, 4]])

In [408]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

In [409]:
z = np.array([[2], [4]])

In [410]:
z.shape

(2, 1)

In [411]:
x / z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [412]:
zz = np.concatenate([z, z], axis=1)

In [413]:
zz

array([[2, 2],
       [4, 4]])

In [414]:
x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [415]:
x = np.array([[1, 3], [2, 4]])
x = x + y
x

array([[ 6,  9],
       [ 9, 12]])

In [416]:
x = np.array([[1, 3], [2, 4]])
x += y
x

array([[ 6,  9],
       [ 9, 12]])

### Elementwise functions

In [417]:
x = np.linspace(-1, 1, 11)

In [418]:
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [419]:
y = np.sin(np.pi * x)

In [420]:
np.round(y, decimals=4) #浮点数设置约束范围

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [421]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [422]:
np.sin(x) ** 2 + np.cos(x) ** 2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [423]:
def heaviside(x):
    return 1 if x > 0 else 0

In [424]:
heaviside(-1)

0

In [425]:
heaviside(1.5)

1

In [426]:
x = np.linspace(-5, 5, 11)

In [427]:
heaviside = np.vectorize(heaviside)

In [428]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [429]:
def heaviside(x):
    return 1.0 * (x > 0)

### Aggregate functions

In [430]:
data = np.random.normal(size=(15,15)) #聚合函数计算

In [431]:
np.mean(data) #均值

-0.03553725315609845

In [432]:
data.mean()

-0.03553725315609845

In [433]:
data = np.random.normal(size=(5, 10, 15))

In [434]:
data.sum(axis=0).shape

(10, 15)

In [435]:
data.sum(axis=(0, 2)).shape

(10,)

In [436]:
data.sum() #求和

23.67485162850373

In [437]:
data = np.arange(1,10).reshape(3,3) 

In [438]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [439]:
data.sum()

45

In [440]:
data.sum(axis=0)

array([12, 15, 18])

In [441]:
data.sum(axis=1)

array([ 6, 15, 24])

### Boolean arrays and conditional expressions

In [442]:
a = np.array([1, 2, 3, 4])

In [443]:
b = np.array([4, 3, 2, 1])

In [444]:
a < b #布尔条件运算

array([ True,  True, False, False])

In [445]:
np.all(a < b)

False

In [446]:
np.any(a < b)

True

In [447]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding element in b")
elif np.any(a < b):
    print("Some elements in a are smaller than their corresponding elemment in b")
else:
    print("All elements in b are smaller than their corresponding element in a")

Some elements in a are smaller than their corresponding elemment in b


In [448]:
x = np.array([-2, -1, 0, 1, 2])

In [449]:
x > 0

array([False, False, False,  True,  True])

In [450]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [451]:
x * (x > 0)

array([0, 0, 0, 1, 2])

In [452]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

In [453]:
x = np.linspace(-5, 5, 11)

In [454]:
pulse(x, position=-2, height=1, width=5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [455]:
pulse(x, position=1, height=1, width=5)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [456]:
def pulse(x, position, height, width):
    return height * np.logical_and(x >= position, x <= (position + width))

In [457]:
x = np.linspace(-4, 4, 9)

In [458]:
np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [459]:
np.select([x < -1, x < 2, x >= 2],
          [x**2  , x**3 , x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [460]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], 
          [x**2,    x**3,    x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [461]:
x[abs(x) > 2]

array([-4., -3.,  3.,  4.])

In [462]:
np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8], dtype=int64),)

In [463]:
x[np.nonzero(abs(x) > 2)]

array([-4., -3.,  3.,  4.])

# Set operations

In [464]:
a = np.unique([1,2,3,3])#取数组中出现过的值，取掉重复值
a

array([1, 2, 3])

In [465]:
b = np.unique([2,3,4,4,5,6,5])

In [466]:
np.in1d(a, b)

array([False,  True,  True])

In [467]:
1 in a

True

In [468]:
1 in b

False

In [469]:
np.all(np.in1d(a, b))

False

In [470]:
np.union1d(a, b) #联合a和b的值

array([1, 2, 3, 4, 5, 6])

In [471]:
np.intersect1d(a, b) #取a和b的共同出现的值

array([2, 3])

In [472]:
np.setdiff1d(a, b) #取a中出现但是b中没有出现的值

array([1])

In [473]:
np.setdiff1d(b, a) #取b中出现但是a中没有出现的值

array([4, 5, 6])

### Operations on arrays

In [474]:
data = np.arange(9).reshape(3, 3)

In [475]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [476]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [477]:
data = np.random.randn(1, 2, 3, 4, 5)

In [478]:
data.shape

(1, 2, 3, 4, 5)

In [479]:
data.T.shape

(5, 4, 3, 2, 1)

## Matrix and vector operations

In [480]:
A = np.arange(1, 7).reshape(2, 3)

In [481]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [482]:
B = np.arange(1, 7).reshape(3, 2)

In [483]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [484]:
np.dot(A, B) #点乘计算

array([[22, 28],
       [49, 64]])

In [485]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [486]:
A = np.arange(9).reshape(3, 3)

In [487]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [488]:
x = np.arange(3)

In [489]:
x

array([0, 1, 2])

In [490]:
np.dot(A, x)

array([ 5, 14, 23])

In [491]:
A.dot(x)

array([ 5, 14, 23])

In [492]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)
A

array([[0.92532339, 0.45320061, 0.2076758 ],
       [0.04251864, 0.02558445, 0.75952399],
       [0.12393358, 0.54600988, 0.86813789]])

In [493]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))

In [494]:
Ap = B.dot(A.dot(np.linalg.inv(B)))

In [495]:
A = np.matrix(A)
A

matrix([[0.92532339, 0.45320061, 0.2076758 ],
        [0.04251864, 0.02558445, 0.75952399],
        [0.12393358, 0.54600988, 0.86813789]])

In [496]:
B = np.matrix(B)

In [497]:
Ap = B * A * B.I

In [498]:
A = np.asmatrix(A)

In [499]:
B = np.asmatrix(B)

In [500]:
Ap = B * A * B.I

In [501]:
Ap = np.asarray(Ap)

In [502]:
np.inner(x, x)

5

In [503]:
np.dot(x, x)

5

In [504]:
y = x[:, np.newaxis]

In [505]:
y

array([[0],
       [1],
       [2]])

In [506]:
np.dot(y.T, y)

array([[5]])

In [507]:
x = np.array([1, 2, 3])

In [508]:
np.outer(x, x) #①对于多维向量，全部展开变为一维向量②第一个参数表示倍数，使得第二个向量每次变为几倍。③第一个参数确定结果的行，第二个参数确定结果的列

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [509]:
np.kron(x, x) 

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [510]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])#newaxis插入新维度

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [511]:
np.kron(np.ones((2,2)), np.identity(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [512]:
np.kron(np.identity(2), np.ones((2,2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [513]:
x = np.array([1, 2, 3, 4])

In [514]:
y = np.array([5, 6, 7, 8])

In [515]:
np.einsum("n,n", x, y)

70

In [516]:
np.inner(x, y)#求内积

70

In [517]:
A = np.arange(9).reshape(3, 3)

In [518]:
B = A.T

In [519]:
np.einsum("mk,kn", A, B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [520]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

True