# 2.6矢量化表达式

In [1]:
import numpy as np

# 2.6.1数组算术运算

In [2]:

x = np.array([[1, 2], [3, 4]])

In [3]:
y = np.array([[5, 6], [7, 8]])

In [4]:
x + y 

array([[ 6,  8],
       [10, 12]])

In [5]:
 y - x

array([[4, 4],
       [4, 4]])

In [6]:
x * y 

array([[ 5, 12],
       [21, 32]])

In [7]:
 y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [8]:

x * 2 #标量的乘法

array([[2, 4],
       [6, 8]])

In [9]:
 2 ** x 

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [10]:
 y / 2 

array([[2.5, 3. ],
       [3.5, 4. ]])

In [11]:
 (y / 2).dtype 

dtype('float64')

In [12]:
###########
#如果数组对大小或形状不兼容的数组执行算术运算，则引发ValueError异常：
x = np.array([1, 2, 3, 4]).reshape(2, 2) #改变数组维度(重新调整矩阵的行数、列数、维数,改为2*2的数组）

In [13]:
z = np.array([1, 2, 3, 4])

In [14]:
 x / z #后缘维度不同，x维度为2，z维度为4，无法与形状（2,2）（4，）一起广播

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [16]:
z.shape

(1, 2)

In [17]:
 x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [18]:

zz = np.concatenate([z, z], axis=0)

In [19]:
zz

array([[2, 4],
       [2, 4]])

In [20]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

In [21]:
 
z = np.array([[2], [4]])

In [22]:
z.shape

(2, 1)

In [23]:
x / z 

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [24]:
zz = np.concatenate([z, z], axis=1) 

In [25]:
zz

array([[2, 2],
       [4, 4]])

In [26]:
 x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [27]:
x = x + y

In [28]:
 x += y

# 2.6.2元素函数

In [29]:
x = np.linspace(-1, 1, 11) 

In [30]:
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [31]:
 y = np.sin(np.pi * x) 

In [32]:
np.round(y, decimals=4) 

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [33]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
 np.sin(x) ** 2 + np.cos(x) ** 2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
def heaviside(x):
    return 1 if x > 0 else 0

In [36]:
heaviside(-1)

0

In [37]:
heaviside(1.5)

1

In [38]:
#但赫德赛维函数不不适用numpy数组输入，会出现报错，例如：
x = np.linspace(-5, 5, 11) #构建数组x,从-5—5之间划分11份

In [39]:
 heaviside(x)
#报错理由：具有多个元素的数组的真值不明确。

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [40]:
heaviside = np.vectorize(heaviside)

In [41]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [42]:
def heaviside(x):
    return 1.0 * (x > 0)

# 2.6.3 聚合函数

In [43]:

data = np.random.normal(size=(15,15)) 

In [44]:
 np.mean(data) 

0.12062517837735648

In [45]:
 data.mean() 

0.12062517837735648

In [46]:
data = np.random.normal(size=(5, 10, 15)) 

In [47]:
 data.sum(axis=0).shape 

(10, 15)

In [48]:
data.sum(axis=(0, 2)).shape 

(10,)

In [49]:
data.sum() 

-17.539620943699845

In [50]:
data = np.arange(1,10).reshape(3,3)

In [51]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
 data.sum()

45

In [53]:
data.sum(axis=0)#按列方向加和

array([12, 15, 18])

In [54]:
data.sum(axis=1) #按行方向加和

array([ 6, 15, 24])

# 2.6.4布尔数组和条件表达式

In [55]:
a = np.array([1, 2, 3, 4])

In [56]:
 b = np.array([4, 3, 2, 1])

In [57]:
a < b

array([ True,  True, False, False])

In [58]:
np.all(a < b)

False

In [59]:
np.any(a < b)

True

In [60]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding element in b")
elif np.any(a < b):
     print("Some elements in a are smaller than their corresponding element in b")
else:
    print("All elements in b are smaller than their corresponding element in a")                

Some elements in a are smaller than their corresponding element in b


In [61]:
x = np.array([-2, -1, 0, 1, 2])

In [62]:
 x > 0

array([False, False, False,  True,  True])

In [63]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [64]:
x * (x > 0)

array([0, 0, 0, 1, 2])

In [65]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

In [66]:
 x = np.linspace(-5, 5, 11)

In [67]:
 pulse(x, position=1, height=1, width=5)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [68]:
def pulse(x, position, height, width):
    return height * np.logical_and(x >= position, x <= (position + width))

In [69]:
x = np.linspace(-4, 4, 9)


In [70]:
 np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [71]:
np.select([x < -1, x < 2, x >= 2],
          [x**2 , x**3 , x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [72]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2],
            [x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [73]:
np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8], dtype=int64),)

In [74]:
x[np.nonzero(abs(x) > 2)]

array([-4., -3.,  3.,  4.])

In [75]:
x[abs(x) > 2]

array([-4., -3.,  3.,  4.])

# 2.6.5设置操作

In [76]:
a = np.unique([1, 2, 3, 3])

In [77]:
b = np.unique([2, 3, 4, 4, 5, 6, 5])

In [78]:
np.in1d(a, b)

array([False,  True,  True])

In [79]:
1 in a

True

In [80]:
1 in b

False

In [81]:
np.all(np.in1d(a, b)) 

False

In [82]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [83]:
np.intersect1d(a, b)

array([2, 3])

In [84]:
np.setdiff1d(a, b)

array([1])

In [85]:

np.setdiff1d(b, a)

array([4, 5, 6])

# 2.6.6对矩阵的操作

In [86]:
data = np.arange(9).reshape(3, 3)

In [87]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [89]:
data = np.random.randn(1, 2, 3, 4, 5)

In [90]:
data.shape

(1, 2, 3, 4, 5)

In [91]:
data.T.shape

(5, 4, 3, 2, 1)

# 2.7向量与矩阵的运算

In [92]:
A = np.arange(1, 7).reshape(2, 3)

In [93]:
 A

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
B = np.arange(1, 7).reshape(3, 2)

In [95]:
 B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [96]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [97]:

np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [98]:
#A = np.arange(9).reshape(3, 3)

In [99]:
 A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
x = np.arange(3)

In [101]:
 x

array([0, 1, 2])

In [102]:
np.dot(A, x)

array([ 5, 14, 23])

In [103]:
A.dot(x)

array([ 5, 14, 23])

In [104]:
A = np.random.rand(3,3)

In [105]:
 B = np.random.rand(3,3)

In [106]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))

In [107]:
Ap = B.dot(A.dot(np.linalg.inv(B)))

In [108]:
A = np.matrix(A)

In [109]:
 B = np.matrix(B)

In [110]:
Ap = B * A * B.I

In [111]:
A = np.asmatrix(A)

In [112]:
 B = np.asmatrix(B)

In [113]:
 Ap = B * A * B.I

In [114]:
Ap = np.asarray(Ap)

In [115]:
np.inner(x, x)

5

In [116]:
np.dot(x, x)

5

In [117]:
y = x[:, np.newaxis]

In [118]:
y

array([[0],
       [1],
       [2]])

In [119]:
np.dot(y.T, y)

array([[5]])

In [120]:
x = np.array([1, 2, 3])

In [121]:
np.outer(x, x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [122]:
np.kron(x, x)

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [123]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [124]:
np.kron(np.ones((2,2)), np.identity(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [125]:
np.kron(np.identity(2), np.ones((2,2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [126]:
x = np.array([1, 2, 3, 4])

In [127]:
y = np.array([5, 6, 7, 8])

In [128]:
np.einsum("n,n", x, y)

70

In [129]:
np.inner(x, y)

70

In [130]:
A = np.arange(9).reshape(3, 3)

In [131]:
 B = A.T

In [132]:
 np.einsum("mk,kn", A, B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [133]:

np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

True

# 2.9Numpy实例练习

In [134]:
# 实例1

In [135]:
import numpy as np

arr1 = np.array([[0, 0, 0],[1, 1, 1],[2, 2, 2], [3, 3, 3]])  #arr1.shape = (4,3)
arr2 = np.array([1, 2, 3])    #arr2.shape = (3,)
arr_sum = arr1 + arr2
print(arr_sum)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [136]:
#实例2

In [137]:
import numpy as np

# 2
data=np.ones((5,5))
print(data)
data[[1,2,3],:]=0
print(data)
data[:,[0,4]]=1
print(data)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [138]:
#实例3

In [139]:
data=np.arange(0,11)
print(data)
data=np.where(data>1,0-(data),data)
data=np.where(data<-9,0-data,data)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1 -2 -3 -4 -5 -6 -7 -8 -9 10]


In [140]:
#实例4

In [141]:
import numpy as np 
 
a = np.array([[1,1,1],[0,2,5],[2,5,-1]]) 
 
print ('数组 A：')
print (a)
ainv = np.linalg.inv(a) 
 
print ('A 的逆：')
print (ainv)
 
print ('矩阵 Y：')
y = np.array([[6],[-4],[27]]) 
print (y)
 
print ('计算：A^(-1)Y：')
x = np.linalg.solve(a,y) 
print("通过np.linalg.solve(a,y)计算得：")
print (x)
# 这就是线性方向 x = 5, y = 3, z = -2 的解
# 结果也可以使用以下函数获取
print("通过np.dot(ainv,y)计算得：")
x2 = np.dot(ainv,y)
print(x2)

数组 A：
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
A 的逆：
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
矩阵 Y：
[[ 6]
 [-4]
 [27]]
计算：A^(-1)Y：
通过np.linalg.solve(a,y)计算得：
[[ 5.]
 [ 3.]
 [-2.]]
通过np.dot(ainv,y)计算得：
[[ 5.]
 [ 3.]
 [-2.]]
