# 2.2numpy数组对象
例1 数组的属性

In [122]:
 import numpy as np

In [123]:
data = np.array([[[1, 2], 
                  [3, 4], 
                  [5, 6]], 
                 [[1, 2], 
                  [3, 4], 
                  [5, 6]]])


In [124]:
 type(data)

numpy.ndarray

In [125]:
data

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [126]:
data.ndim#数组维度

3

In [127]:
data.shape#数组形状

(2, 3, 2)

In [128]:
 data.size#数组中所有的元素

12

In [129]:
data.dtype#数组中的数据类型

dtype('int32')

In [130]:
data.nbytes#数组中的字节数

48

# 2.2.1数据类型
例1 dtype生成不同数据类型

In [10]:
 np.array([1, 2, 3], dtype=np.int)

array([1, 2, 3])

In [11]:
 np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [12]:
 np.array([1, 2, 3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

例2：用np.array函数转换数组类型

In [13]:
data = np.array([1, 2, 3], dtype=np.float)

In [14]:
data

array([1., 2., 3.])

In [15]:
data.dtype

dtype('float64')

In [16]:
 data = np.array(data, dtype=np.int)

In [17]:
 data.dtype

dtype('int32')

In [18]:
data

array([1, 2, 3])

 或者使用ndarray类的astype方法:

In [19]:
data = np.array([1, 2, 3], dtype=np.float)

In [20]:
data

array([1., 2., 3.])

In [21]:
 data.astype(np.int)

array([1, 2, 3])

 例3：数组计算时，数据类型会改变

In [22]:
 d1 = np.array([1, 2, 3], dtype=float)

In [23]:
 d2 = np.array([1, 2, 3], dtype=complex)

In [24]:
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [25]:
(d1 + d2).dtype#浮点数组和复值数组相加是复值数组

dtype('complex128')

例4：在某些必要的时候将数组设置成某种类型

In [26]:
np.sqrt(np.array([-1, 0, 1]))#np.sqrt对数组求每个元素的平方根，会根据不同数据类型给出不同结果。

D:\Download\python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [53]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

# 2.2.2 复数的虚部和实部
例1用real 和imag提取数组的实部和虚部

In [64]:
data = np.array([1, 2, 3], dtype=complex)

In [65]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [66]:
data.real

array([1., 2., 3.])

In [67]:
data.imag

array([0., 0., 0.])

# 2.3.1 创建数组
例1 用array创建一维数组（来源于python列表，或者其他数组对象）

In [133]:
np.array([1, 2, 3, 4])#list

array([1, 2, 3, 4])

In [71]:
data=np.array([1, 2, 3, 4])
data.ndim

1

In [87]:
data.shape

(4,)

创建一个二维数组:

In [73]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [75]:
data=np.array([[1, 2], [3, 4]])
data.ndim

2

In [76]:
data.shape

(2, 2)

# 2.3.2用常量填充的数组（0,1）
例1

In [83]:
 np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [78]:
 np.ones(4)

array([1., 1., 1., 1.])

例2：np.zero和np.one函数默认的数据类型为float64,可以用dtype更改参数类型

In [79]:
data = np.ones(4)

In [80]:
 data.dtype

dtype('float64')

In [81]:
 data = np.ones(4, dtype=np.int64)

In [82]:
data.dtype

dtype('int64')

例3:使用任意常数值填充的数组（两种方法）

In [134]:
 x1 = 5.4 * np.ones(10)#使用乘法

In [135]:
x2 = np.full(10, 5.4)#避免了乘法，效率更高，构造一个指定值填充的数组（shape即几个元素，填充的值）

In [136]:
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [137]:
x2

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

例4：用np.fill函数填充常数值

In [138]:
 x1 = np.empty(5)#构造一个给定大小的未初始化数组

In [139]:
x1.fill(3.0)#（填充的值）

In [140]:
x1

array([3., 3., 3., 3., 3.])

In [141]:
x2 = np.full(5, 3.0)#另一种方法

In [90]:
x2

array([3., 3., 3., 3., 3.])


# 2.3.3用递增序列填充的数组
例1：np.arrage和np.linspace来创建

In [172]:
np.arange(0.0, 10, 1)#（起始数，终止数，以1为间隔，但不包含结束值10）


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [92]:
np.linspace(0, 10, 11)#（起始数，终止数，总数）#增量为非整数一般用这个

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# 2.3.4用对数序列填充的数组
例1：生成值在1到100之间的对数分布数组

In [167]:
np.logspace(0, 2, 5) # 产生从10的0次幂到10的2次幂、有5个元素的等比数列

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

# 2.3.5网格点坐标矩阵
例1利用np .meshgrid函数把低维数组生成多维数组

In [97]:
x = np.array([-1, 0, 1])

In [98]:
y = np.array([-2, 2])

In [99]:
 X, Y = np.meshgrid(x, y)

In [102]:
X#x进行行堆叠，因为需要形成（x,y）的每一个点，x轴上需要形成2维数组，形状就是2x3

array([[-1,  0,  1],
       [-1,  0,  1]])

In [103]:
Y#y进行列堆叠

array([[-2, -2, -2],
       [ 2,  2,  2]])

例2：二维坐标数组的常见用例：对两个变量上的函数求值。计算表达式(x+y)的平方对x和y数组中所有组合值的值

In [104]:
 Z = (X + Y) ** 2

In [105]:
Z

array([[9, 4, 1],
       [1, 4, 9]], dtype=int32)

# 2.3.6创建未初始化数组
np.empty创建具有特定大小和数据类型的数组，但不将数组中的元素初始化为任何特定值

In [181]:
np.empty(3, dtype=np.float)#和结果不一样 因为创建具有特定大小和数据类型的数组，但不将数组中的元素初始化为任何特定值。这就容易出现错误，使用np.zeros会更安全一些

array([2.12199579e-314, 6.36598737e-314, 1.06099790e-313])

# 2.3.7创建具有其他数组属性的数组
使用np.ones_like, np.zeros_like, np.full_like, np.empty_like创建与另一个数组共享属性(如形状和数据类型)的新数组

In [ ]:
def f(x):
y = np.ones_like(x)
# compute with x and y
return y
#在函数体的第一行，使用np.ones_like创建一个新的数组y,它产生一个与x大小和数据类型相同的数组，并填充为1。

# 2.3.8创建矩阵数组
例1：用np.identity函数生成一个对角线上为1，其他地方为0的方阵

In [105]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

例2：numpy.eye生成对角上和对角下的非零对角矩阵

In [106]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [109]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

例3：np.diag构造一个具有任意对角一维数组的矩阵，也接受可选关键字参数k来指定对角偏移量。

In [110]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

# 2.4索引和切片
2.4.1一维数组
例1:创建一维数组

In [147]:
 a = np.arange(0, 11)#步长默认为1

In [148]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

例2：一维数组索引

In [35]:
 a[0] # the first element

0

In [36]:
 a[-1] # the last element

10

In [37]:
a[4] # the fifth element, at index 4

4

例3：一维数组切片：选择元素范围

In [38]:
a[1:-1]#-1是指倒数第1个元素[m:n]即第m+1到n-1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
 a[1:-1:2]

array([1, 3, 5, 7, 9])

例4：选择前五或者后五个数

In [118]:
 a[:5]#忽略的数表示默认为数组开始或结束

array([0, 1, 2, 3, 4])

In [119]:
 a[-5:]#从-5开始往后数

array([ 6,  7,  8,  9, 10])

例5：反转数组

In [120]:
a[::-2]

array([10,  8,  6,  4,  2,  0])

# 2.4.2多维数组
例1创建一个二维数组

In [114]:
f = lambda m, n: n + 10 * m 

In [175]:
A = np.fromfunction(f, (6, 6), dtype=int)
#help(np.fromfunction)

In [45]:
A#通过以上两个函数创建了一个二维数组6x6

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

例2：提取行和列

In [46]:
 A[:, 1] # the second column0为第一列

array([ 1, 11, 21, 31, 41, 51])

In [47]:
A[1, :] # the second row

array([10, 11, 12, 13, 14, 15])

例3：切片，提取子数组

In [48]:
 A[:3, :3] # 上半对角矩阵

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [49]:
 A[3:, :3] #左下非对角块矩阵

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

例4：元素间隔不超过1 时，

In [50]:
 A[::2, ::2]#步长为2

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [51]:
 A[1::2, 1::3]#

array([[11, 14],
       [31, 34],
       [51, 54]])

# 2.4.3视图
例1子数组和原始数组的关系

In [52]:
 B = A[1:5, 1:5]#提取子数组会得到视图，而非新的独立数组

In [53]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [54]:
 B[:, :] = 0#子数组赋予新值  

In [55]:
A#两个数组引用内存中的相同数据

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

例2：当需要一个副本而非视图时，用copy法来复制视图

In [56]:
C = B[1:3, 1:3].copy()

In [57]:
C

array([[0, 0],
       [0, 0]])

In [58]:
C[:, :] = 1 # 这里不会影响到b

In [59]:
C

array([[1, 1],
       [1, 1]])

In [60]:
B#用np.array，关键字参数copy=true，也可以做到

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# 2.4.4花式索引和布尔值索引
例1用另一numpy数组建立索引,要求索引的数组或别表中的元素都是整数。

In [148]:
A = np.linspace(0, 1, 11)

In [149]:
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [144]:
A[np.array([0, 2, 4])]#索引A中的第0,2,4个元素

array([0. , 0.2, 0.4])

In [145]:
 A[[0, 2, 4]] 

array([0. , 0.2, 0.4])

例2：布尔值索引数组

In [150]:
A > 0.5#当从数组中过滤出元素时，布尔索引方法非常方便

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [151]:
 A[A > 0.5]#

array([0.6, 0.7, 0.8, 0.9, 1. ])

例3花式索引和布尔索引返回的数组是新的独立数组，而非视图

In [154]:
A = np.arange(10)

In [152]:
indices = [2, 4, 6]#建立一个索引位置

In [153]:
B = A[indices]
B

array([2, 4, 6])

In [155]:
B[0] = -1 # this does not affect A
B

array([-1,  4,  6])

In [156]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
 A[indices] = -1 # this alters A

In [158]:
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

同样，对于布尔值索引:

In [156]:
 A = np.arange(10)

In [157]:
B = A[A > 5]
B

array([6, 7, 8, 9])

In [158]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
 A[A > 5] = -1 # this alters A大于5的元素都为-1

In [163]:
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

# 2.5重塑和调整
例1用reshape 和 ndarray的方法重塑（重塑数组会产生数组的视图，如果需要数组的独立副本，则必须显式地复制视图(例如，使用np.copy)。

In [160]:
 data = np.array([[1, 2], [3, 4]])

In [161]:
 np.reshape(data, (1, 4))#reshape方法，改变数组形状，2x2变为1x4的二维数组

array([[1, 2, 3, 4]])

In [162]:
data.reshape(4)#ndarray方法，改变数组维度，变为元素数量一样的一维数组

array([1, 2, 3, 4])

例2：重塑的特殊情况——np.ravel及其对应的ndarray方法flatten，一个返回视图一个返回副本

In [167]:
data = np.array([[1, 2], [3, 4]])

In [168]:
data

array([[1, 2],
       [3, 4]])

In [164]:
data.ravel()#ravel折叠成一维，返回视图
#或者data.flatten()

array([1, 2, 3, 4])

In [165]:
 data.flatten().shape#flatten折叠成一维，返回副本

(4,)

例3用np.reshape添加新轴或np.newaxis

In [172]:
data = np.arange(0, 5)

In [173]:
column = data[:, np.newaxis]#添加数轴，相当于np.expand_dims(data, axis=1)

In [174]:
 column#5x1

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [175]:
 row = data[np.newaxis, :]#相当于np.expand_dims(data, axis=0)

In [176]:
row#1x5

array([[0, 1, 2, 3, 4]])

例4用np.vstack垂直地对数组进行堆叠

In [177]:
 data = np.arange(5)

In [178]:
data

array([0, 1, 2, 3, 4])

In [179]:
 np.vstack((data, data, data))#垂直地对它们进行堆叠，以获得一个矩阵，其中的行是由一维数组组成的

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

例5np.hstack对数组进行水平堆叠

In [117]:
data = np.arange(5)

In [118]:
data

array([0, 1, 2, 3, 4])

In [119]:
np.hstack((data, data, data))#相反，如果我们想要水平堆叠数组，以获得一个数组是列向量的矩阵

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

例6np.hstack将输入的数组视为列并进行堆叠，如果需要二维而非一维数组，则先插入一个新轴再进行水平堆叠

In [120]:
data = data[:, np.newaxis]
data

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [185]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])