In [1]:
#Vectors,Matrices,and Multidimensional Arrays

In [2]:
#Importing the Modules

In [3]:
import numpy as np

In [4]:
#The Numpy Array Object

In [6]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [7]:
type(data)

numpy.ndarray

In [9]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
data.ndim

2

In [11]:
data.shape

(3, 2)

In [12]:
data.size

6

In [13]:
data.dtype

dtype('int64')

In [14]:
data.nbytes

48

In [15]:
#Data Types

In [16]:
np.array([1, 2, 3], dtype = np.int )

array([1, 2, 3])

In [17]:
np.array([1, 2, 3], dtype = np.float )

array([1., 2., 3.])

In [18]:
np.array([1, 2, 3], dtype = np.complex )

array([1.+0.j, 2.+0.j, 3.+0.j])

In [19]:
data = np.array([1, 2, 3], dtype = np.float )

In [20]:
data

array([1., 2., 3.])

In [21]:
data.dtype

dtype('float64')

In [22]:
data.astype(np.int)

array([1, 2, 3])

In [23]:
d1 = np.array([1, 2, 3], dtype = float )

In [24]:
d2 = np.array([1, 2, 3], dtype = complex )

In [25]:
d1+d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [26]:
(d1+d2).dtype

dtype('complex128')

In [27]:
np.sqrt(np.array([-1, 0, 1]))

<ipython-input-27-18cc2be45d00>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np.array([-1, 0, 1]))


array([nan,  0.,  1.])

In [28]:
np.sqrt(np.array([-1, 0, 1], dtype = complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

In [29]:
#Real and Imaginary Parts

In [30]:
data = np.array([1, 2, 3], dtype = complex )

In [31]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [32]:
data.real

array([1., 2., 3.])

In [34]:
data.imag

array([0., 0., 0.])

In [36]:
#Arrays Created from Lists and Other Array-Like Objects

In [48]:
data = np.array([1, 2, 3, 4])

In [49]:
data.ndim

1

In [50]:
data.shape

(4,)

In [52]:
data = np.array([[1, 2], [3, 4]])

In [53]:
data.ndim

2

In [54]:
data.shape

(2, 2)

In [55]:
#Arraya Filled with Constant Values 

In [56]:
data = np.zeros((2, 3))

In [57]:
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
data = np.ones(4)

In [59]:
data

array([1., 1., 1., 1.])

In [60]:
data.dtype

dtype('float64')

In [61]:
data = np.ones(4, dtype = np.int64)

In [62]:
data.dtype

dtype('int64')

In [63]:
x1 = np.empty(5) 

In [64]:
x1.fill(3.0)

In [65]:
x1

array([3., 3., 3., 3., 3.])

In [67]:
x2 = np.full(5, 3.0)

In [68]:
x2

array([3., 3., 3., 3., 3.])

In [69]:
#Arrays Filled with Incremental equences

In [72]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [73]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [74]:
#Arrays Filled with Logarithmic sequences

In [75]:
np.logspace(0, 2, 5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [76]:
#Meshgrid Arrays

In [82]:
x = np.array([-1, 0, 1])

In [83]:
y = np.array([-2, 0, 2])

In [84]:
X, Y = np.meshgrid(x, y)

In [85]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [86]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [87]:
Z = (X + Y) ** 2

In [88]:
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

In [89]:
#Creating Uninitialized Arrays

In [91]:
a = np.empty(3, dtype=np.float)

In [92]:
a

array([1., 2., 3.])

In [93]:
#Creating Arrays with Properties of other Arrays

In [94]:
def f(x):
    y = np.ones_like(x)#compute with x and y
    return y 

In [95]:
#Creating Matrix Arrays

In [96]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [97]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [98]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [99]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [100]:
#One-Dimensional Arrays

In [103]:
a=np.arange(0, 11)

In [104]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
a[0]

0

In [106]:
a[-1]

10

In [107]:
a[4]

4

In [108]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [110]:
a[:5]

array([0, 1, 2, 3, 4])

In [111]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [112]:
a[::-2]

array([10,  8,  6,  4,  2,  0])

In [113]:
#Multidimensional Arrays

In [114]:
f=lambda m, n: n + 10 * m

In [115]:
A=np.fromfunction(f, (6, 6), dtype=int)

In [116]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [117]:
A[:, 1]

array([ 1, 11, 21, 31, 41, 51])

In [118]:
A[1, :]

array([10, 11, 12, 13, 14, 15])

In [119]:
A[:3, :3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [120]:
A[3:, :3]

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [122]:
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [123]:
A[1::2, 1::3]

array([[11, 14],
       [31, 34],
       [51, 54]])

In [124]:
B=A[1:5, 1:5]

In [125]:
B


array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [126]:
B[:, :]=0

In [127]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [128]:
C=B[1:3, 1:3].copy()

In [129]:
C

array([[0, 0],
       [0, 0]])

In [130]:
C[:, :]=1

In [131]:
C

array([[1, 1],
       [1, 1]])

In [132]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [133]:
#Fancy Indexing and Boolean-Valued Indexing

In [134]:
A=np.linspace(0, 1, 11)

In [135]:
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [136]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [137]:
A[[0, 2, 4]]

array([0. , 0.2, 0.4])

In [138]:
A>0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [139]:
A[A>0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [148]:
A=np.arange(10)

In [149]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
indices=[2, 4, 6]

In [151]:
B=A[indices]

In [152]:
B

array([2, 4, 6])

In [153]:
B[0]=-1

In [154]:
B

array([-1,  4,  6])

In [155]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
A=np.arange(10)

In [157]:
B=A[A>5]

In [158]:
B

array([6, 7, 8, 9])

In [159]:
B[0]=-1

In [160]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
A[A>5]=-1

In [162]:
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

In [163]:
#Reshaping and Resizing

In [164]:
data=np.array([[1, 2], [3, 4]])

In [165]:
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [170]:
data.reshape(4)

array([1, 2, 3, 4])

In [181]:
data=np.arange(0, 5)

In [182]:
data

array([0, 1, 2, 3, 4])

In [183]:
column=data[:, np.newaxis]

In [184]:
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [185]:
row=data[np.newaxis, :]

In [186]:
row

array([[0, 1, 2, 3, 4]])

In [187]:
data=np.arange(5)

In [188]:
data

array([0, 1, 2, 3, 4])

In [189]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [190]:
data=data[:, np.newaxis]

In [191]:
data

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [192]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [193]:
#Arithmetic Operations

In [201]:
x=np.array([[1, 2], [3, 4]])

In [202]:
y=np.array([[5, 6], [7, 8]])

In [203]:
x+y

array([[ 6,  8],
       [10, 12]])

In [204]:
y-x

array([[4, 4],
       [4, 4]])

In [205]:
x*y

array([[ 5, 12],
       [21, 32]])

In [206]:
y/x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [207]:
x*2

array([[2, 4],
       [6, 8]])

In [208]:
2**x

array([[ 2,  4],
       [ 8, 16]])

In [209]:
y/2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [210]:
(y/2).dtype

dtype('float64')

In [211]:
z = np.array([[2, 4]])


In [212]:
z.shape

(1, 2)

In [213]:
x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [214]:
zz = np.concatenate([z, z], axis=0)

In [215]:
zz

array([[2, 4],
       [2, 4]])

In [216]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

In [217]:
x = x + y


In [218]:
x

array([[ 6,  8],
       [10, 12]])

In [219]:
x += y

In [220]:
x

array([[11, 14],
       [17, 20]])

In [221]:
#Elementwise Functions

In [222]:
x = np.linspace(-1, 1, 11)
x


array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [223]:
y = np.sin(np.pi * x)

In [224]:
y

array([-1.22464680e-16, -5.87785252e-01, -9.51056516e-01, -9.51056516e-01,
       -5.87785252e-01,  0.00000000e+00,  5.87785252e-01,  9.51056516e-01,
        9.51056516e-01,  5.87785252e-01,  1.22464680e-16])

In [225]:
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [226]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)



array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [227]:
np.sin(x) ** 2 + np.cos(x) ** 2


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [229]:
def heaviside(x):
    return 1 if x > 0 else 0

In [230]:
heaviside(-1)

0

In [231]:
heaviside(1.5)



1

In [232]:
heaviside = np.vectorize(heaviside)

In [233]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [234]:
#Aggregate Functions

In [235]:
data = np.random.normal(size=(15,15))


In [236]:
data

array([[ 4.94628657e-01,  1.58344816e-01,  3.38615414e-01,
         1.87673872e-01, -2.47772864e-02,  4.32303302e-01,
        -9.77121641e-01,  2.05490764e-01,  7.01999032e-01,
        -1.82267254e-01, -3.24643531e-01, -3.97943266e-01,
        -1.16010317e-01,  3.67600760e-01, -2.14210875e-01],
       [ 2.13333372e+00, -5.72127198e-03,  1.55470368e+00,
        -2.68372038e-01,  1.48255499e-01, -8.77757055e-01,
         8.71443678e-01, -9.36054349e-01,  3.62731040e-01,
        -1.29325305e+00, -5.11880551e-01,  3.32237454e-01,
        -2.57324163e-01,  1.80145069e+00,  2.88205461e-01],
       [-6.33052562e-01,  3.90361758e-01,  1.37427453e-01,
         1.32410398e+00, -1.32989584e-03, -9.77825581e-01,
        -6.08054906e-01, -9.05273607e-01, -1.22163915e+00,
         1.91030343e+00,  1.47436217e+00,  1.96709163e+00,
        -1.53674200e+00, -1.32348549e+00,  3.22447612e-01],
       [-1.06783500e+00, -7.69331163e-01,  1.95824563e+00,
        -8.28023852e-01, -3.98604717e-01, -8.69014525

In [237]:
np.mean(data)

0.03944912907634163

In [238]:
data.mean()

0.03944912907634163

In [239]:
data = np.random.normal(size=(5, 10, 15))

In [240]:
data

array([[[ 4.41148940e-01, -1.34970527e+00,  7.78889861e-01,
         -9.14192316e-02,  1.44039617e+00,  1.52955982e-02,
         -1.51207433e+00,  1.84770748e-02, -1.29880543e-01,
         -1.96347177e-01,  9.76816226e-01, -2.12506163e-01,
         -1.91186524e+00,  1.98234690e+00, -1.65881159e+00],
        [-8.16672832e-01, -8.74227493e-01, -2.72656019e-01,
          3.03759088e-01, -1.04611374e+00,  2.12450431e+00,
         -2.53343690e+00,  2.45323595e-01,  2.02657058e-01,
         -4.64158995e-01,  1.78536867e-01, -1.41721327e+00,
         -2.17894657e-01, -7.42571583e-01, -1.72557470e-01],
        [-1.10526062e-02,  1.97724119e+00,  6.38779886e-01,
          1.85325578e-01, -1.32045506e+00, -9.23991271e-01,
          2.41484720e+00,  7.43688815e-01,  1.27944489e+00,
          8.01750924e-01,  3.29944310e-01, -1.84398880e+00,
          9.61099296e-01,  2.46000914e-01,  2.56049650e-01],
        [ 1.38521415e+00, -7.54027788e-01,  2.62522933e-01,
          4.43537479e-01,  7.37197642

In [241]:
data.sum(axis=0).shape

(10, 15)

In [242]:
data.sum(axis=(0, 2)).shape

(10,)

In [243]:
data.sum()

-24.814704594574295

In [244]:
data = np.arange(1,10).reshape(3,3)


In [245]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [246]:
data.sum()

45

In [247]:
data.sum(axis=0)

array([12, 15, 18])

In [248]:
data.sum(axis=1)

array([ 6, 15, 24])

In [249]:
#Boolean Arrays and Conditional Expressions

In [250]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

In [251]:
a < b

array([ True,  True, False, False])

In [252]:
np.all(a < b)

False

In [253]:
np.any(a < b)

True

In [255]:
x = np.array([-2, -1, 0, 1, 2])

In [256]:
x > 0

array([False, False, False,  True,  True])

In [257]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [258]:
x * (x > 0)

array([0, 0, 0, 1, 2])

In [262]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))



In [263]:
x = np.linspace(-5, 5, 11)

In [264]:
x

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [265]:
pulse(x, position=-2, height=1, width=5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [266]:
pulse(x, position=1, height=1, width=5)


array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [267]:
x = np.linspace(-4, 4, 9)

In [268]:
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [269]:
np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [271]:
#Set Operations

In [273]:
a = np.unique([1, 2, 3, 3])

In [274]:
a

array([1, 2, 3])

In [275]:
b = np.unique([2, 3, 4, 4, 5, 6, 5])

In [276]:
b

array([2, 3, 4, 5, 6])

In [277]:
np.in1d(a, b)

array([False,  True,  True])

In [278]:
1 in a

True

In [280]:
1 in b

False

In [281]:
np.all(np.in1d(a, b))

False

In [282]:
In [213]: np.union1d(a, b)


array([1, 2, 3, 4, 5, 6])

In [283]:
np.intersect1d(a, b)

array([2, 3])

In [284]:
np.setdiff1d(a, b)

array([1])

In [285]:
np.setdiff1d(b, a)

array([4, 5, 6])

In [286]:
#Operations on Arrays

In [287]:
data = np.arange(9).reshape(3, 3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [288]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [289]:
data = np.random.randn(1, 2, 3, 4, 5)

In [290]:
data

array([[[[[ 2.48885107e-01,  6.43187833e-01, -2.23384848e-01,
            1.01742848e+00, -2.51971776e+00],
          [-3.07549174e-01,  3.39577766e-02,  3.86152825e-01,
           -5.10117644e-01,  6.88869878e-01],
          [ 1.30335662e+00,  1.41204545e+00, -1.29767782e+00,
           -7.58001664e-01, -2.23739618e+00],
          [ 1.11937100e+00,  1.19914962e+00, -8.87285877e-01,
            2.09327054e-01, -1.01380732e+00]],

         [[-6.18472596e-01,  6.75819396e-01,  1.04581000e+00,
           -2.37650441e-01,  1.19522133e+00],
          [-1.02685116e+00,  3.02594698e-01, -1.57872185e+00,
           -6.63750562e-01,  1.43292097e+00],
          [ 2.14612754e+00,  1.02214848e-01,  6.88826391e-01,
           -8.46039303e-01, -1.56812262e-02],
          [-2.06952695e-01,  5.14282431e-01,  1.62525779e+00,
           -1.21177791e+00, -7.24984005e-01]],

         [[ 9.58115798e-01, -4.65853424e-01,  3.06736664e+00,
           -7.39653843e-01,  1.34325909e+00],
          [ 1.42374202e+

In [291]:
data.shape

(1, 2, 3, 4, 5)

In [292]:
data.T.shape

(5, 4, 3, 2, 1)

In [293]:
#Matrix and Vector Operations

In [294]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [295]:
B = np.arange(1, 7).reshape(3, 2)
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [296]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [297]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [298]:
A = np.arange(9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [299]:
x = np.arange(3)
x

array([0, 1, 2])

In [300]:
np.dot(A, x)

array([ 5, 14, 23])

In [303]:
A = np.random.rand(3,3)

In [304]:
A

array([[0.1390676 , 0.34032861, 0.70253313],
       [0.07709341, 0.74395596, 0.34659212],
       [0.00909708, 0.95373373, 0.79667224]])

In [305]:
B = np.random.rand(3,3)

In [306]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))

In [308]:
Ap

array([[-1.31667524, -0.52377543,  2.80054672],
       [-1.62370155, -0.31130862,  3.01716855],
       [-1.8661556 , -0.34565904,  3.30767965]])

In [309]:
Ap = B.dot(A.dot(np.linalg.inv(B)))

In [310]:
Ap

array([[-1.31667524, -0.52377543,  2.80054672],
       [-1.62370155, -0.31130862,  3.01716855],
       [-1.8661556 , -0.34565904,  3.30767965]])

In [311]:
A = np.matrix(A)

In [312]:
A

matrix([[0.1390676 , 0.34032861, 0.70253313],
        [0.07709341, 0.74395596, 0.34659212],
        [0.00909708, 0.95373373, 0.79667224]])

In [313]:
B = np.matrix(B)

In [314]:
Ap = B * A * B.I

In [315]:
Ap

matrix([[-1.31667524, -0.52377543,  2.80054672],
        [-1.62370155, -0.31130862,  3.01716855],
        [-1.8661556 , -0.34565904,  3.30767965]])

In [316]:
A = np.asmatrix(A)

In [317]:
In [243]: B = np.asmatrix(B)

In [318]:
Ap = B * A * B.I

In [319]:
Ap = np.asarray(Ap)

In [320]:
np.inner(x, x)

5

In [321]:
np.dot(x, x)

5

In [322]:
y = x[:, np.newaxis]
y

array([[0],
       [1],
       [2]])

In [325]:
np.dot(y.T, y)

array([[5]])

In [326]:
x = np.array([1, 2, 3])

In [327]:
np.outer(x, x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [329]:
np.kron(x, x)

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [330]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [331]:
np.kron(np.ones((2,2)), np.identity(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [332]:
np.kron(np.identity(2), np.ones((2,2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [333]:
In [257]: x = np.array([1, 2, 3, 4])

In [334]:
In [258]: y = np.array([5, 6, 7, 8])

In [335]:
In [259]: np.einsum("n,n", x, y)

70

In [336]:
np.inner(x, y)

70

In [344]:
A = np.arange(9).reshape(3, 3)

In [345]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [346]:
B = A.T

In [347]:
B

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [339]:
np.einsum("mk,kn", A, B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [340]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

True